### ISSUE TITLE
bb-wl18xx-tether fails if connman is not present

### ISSUE THREAD

**Issue by mickael9** [RobertCNelson/bb-wl18xx-firmware#1]
Since the script runs with `sh -e`, any error in the script will abort execution. This also includes the folowing line:

```sh
connmanctl_bin=$(which connmanctl)
```

To fix this, ths line can be changed as such :
```sh
connmanctl_bin=$(which connmanctl || true)
```

**Comment by RobertCNelson** [comment]
@mickael9 , sure we can do this, it'll still eventually fail on the missing connmanctl binary. (initially, this deb package required connman by default.)  so we will have to cleanup those situations too.

Regards,

**Comment by mickael9** [comment]
It seems that every other call is shielded by a test of either commanctl binary or service file presence, so it will never actually try to run connman if it's not installed.
