### ISSUE TITLE
"bb-wl18xx-wlan0" still try to launch dnsmasq when I disable USB network

### ISSUE THREAD

**Issue by zhanglongqi** [RobertCNelson/bb-wl18xx-firmware#2]
I set "USB_NETWORK_DISABLED=yes" in `/etc/default/bb-boot` and  `TETHER_ENABLED=no` in `/etc/default/bb-wl18xx`. but the `bb-wl18xx-wlan0.service` still try to launch dnsmasq.
Maybe the script `bb-wl18xx-wlan0` need to check `USB_NETWORK_DISABLED=yes`  before start `dnsmasq` https://github.com/RobertCNelson/bb-wl18xx-firmware/blob/ec2a36b2f117b6ab3920b30e9a4f0aefeaf698aa/debian/bb-wl18xx-wlan0#L196-L198

and in `bb_dnsmasq_config.sh` it did not check `USB_NETWORK_DISABLED`. 
May I know what is the reason? `USB_NETWORK_DISABLED=yes` should mean disable both the USB network right?

**Comment by RobertCNelson** [comment]
Hi @zhanglongqi, you are correct, with those two options set, dnsmasq should not fire up.

Ah too many conditions. ;)

Regards,

**Comment by RobertCNelson** [comment]
and pushed out to the repo, thanks!
