### ISSUE TITLE
Bluetooth not setup in BB Green Gateway

### ISSUE THREAD

**Issue by JoseGoncalves** [RobertCNelson/bb-wl18xx-firmware#4]
On BB Green Gateway the Bluetooth is not setup.
Script `/usr/bin/bb-wl18xx-bluetooth`needs provisioning for board `SeeedStudio_BeagleBone_Green_Gateway`, and something more is missing, because `/sys/class/leds/wl18xx_bt_en` does not appear in this board.

**Comment by RobertCNelson** [comment]
After v4.14.x, this 'should' take care of auto-loading the firmware:

https://github.com/beagleboard/BeagleBoard-DeviceTrees/blob/v4.19.x-ti-overlays/src/arm/am335x-bonegreen-gateway.dts#L159-L162

Regards,

**Comment by JoseGoncalves** [comment]
I'm not talking about firmware, I'm talking about starting the `hciattach` process.
The [bb-wl18xx-bluetooth script](https://github.com/RobertCNelson/bb-wl18xx-firmware/blob/master/debian/bb-wl18xx-bluetooth) does not check for board `SeeedStudio_BeagleBone_Green_Gateway`...

**Comment by RobertCNelson** [comment]
Correct hciattach got replaced by that line i posted:

https://ostconf.com/system/attachments/files/000/001/531/original/serdev-piter-2018.pdf?1540914672

**Comment by JoseGoncalves** [comment]
OK. Thanks for clarifying this for me.

**Comment by RobertCNelson** [comment]
it's not working thou...

**Comment by JoseGoncalves** [comment]
If someone needs to use BT with current OS state, is there any workaround to make it work in BBGG?

**Comment by RobertCNelson** [comment]
Found it, thought it was this:

https://github.com/RobertCNelson/ti-linux-kernel-dev/commit/844226605e422c71652a5e2ad5934bf15be379aa

```
debian@beaglebone:~$ sudo bluetoothctl 
Agent registered
[bluetooth]# list
Controller 64:69:4E:7F:3E:45 beaglebone [default]
[bluetooth]# scan on
Discovery started
[CHG] Controller 64:69:4E:7F:3E:45 Discovering: yes
[NEW] Device 7C:08:03:08:10:65 7C-08-03-08-10-65
```
